# Please consider only editing this file through systemd drop-in files
# (e.g. `systemctl edit seaf-notification-server`). This will enable you to get updates
# to this file automatically, without your overrides being lost.

# Refer to the manpage `systemd.unit` for detailed documentation on each option.
[Unit]
Description=Seafile real-time notification server
Documentation=https://manual.seafile.com https://github.com/dionysius/seafile-deb
PartOf=seafile.target
After=network.target seaf-server.service seafile.target

# If running behind a reverse proxy - running on this system - consider ordering it before also:
#Before=nginx.service

# Refer to the manpages `systemd.service` and `systemd.exec` for detailed documentation on each option.
[Service]
SyslogIdentifier=seaf-notification-server
## Service execution environment
# Service configuration file.
EnvironmentFile=%E/seafile/seafile.env
Type=exec
ExecCondition=/bin/sh -ec '[ "$ENABLE_NOTIFICATION_SERVER" = true ]'
ExecStart=/usr/lib/seafile/bin/notification-server -c %E/seafile -l -
WorkingDirectory=/var/lib/seafile
Restart=on-failure
RestartSec=5s

## Permissions and directories
User=seafile
Group=seafile
ConfigurationDirectory=seafile::ro
ConfigurationDirectoryMode=0500
UMask=0027

## Connection and process limits
LimitNOFILE=1048576
#TasksMax=128
# Customize limits to your setup and expected usage spikes.
#CPUQuota=100%
#MemoryHigh=256M
#MemoryMax=512M

## Sandboxing and isolation
# An overview is available using `systemd-analyze security <service>`.
AmbientCapabilities=
CapabilityBoundingSet=
# Uncomment these to allow binding to ports in the range 0-1024.
#AmbientCapabilities=CAP_NET_BIND_SERVICE
#CapabilityBoundingSet=CAP_NET_BIND_SERVICE

# Process restrictions
NoNewPrivileges=true
RestrictSUIDSGID=true
SecureBits=noroot noroot-locked

# Filesystem protection
ProtectSystem=strict
ProtectHome=true
ProtectProc=noaccess
ProcSubset=pid

# Namespace isolation
PrivateTmp=disconnected
PrivateDevices=true
PrivateIPC=true
#:if SYSTEMD_MAJOR >= 258
PrivateBPF=true
#:endif

# Kernel and system protection
ProtectClock=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectControlGroups=strict

# Execution restrictions
# The go runtime needs writable+executable memory.
MemoryDenyWriteExecute=false
SetLoginEnvironment=false

# System call and network filtering
SystemCallFilter=@system-service
SystemCallArchitectures=native
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
RestrictRealtime=true

# Cleanup
RemoveIPC=true

[Install]
WantedBy=seafile.target
