name: publish release

on:
  workflow_call:

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:

  release:
    uses: dionysius/gbp-gha/.github/workflows/release.yml@main
    with:
      prerelease: true
      publish: true

  promote:
    needs: release
    uses: dionysius/gbp-gha/.github/workflows/promote-release.yml@main
    with:
      in_days: 3
      release_pattern: '{debian/*.*}.*'
